# Generated by Django 4.1 on 2023-05-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KakaoFriend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=200)),
                ("job", models.CharField(max_length=200)),
                ("age", models.IntegerField(default=0)),
            ],
        ),
    ]
