# Generated by Django 4.1 on 2023-05-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="user_id"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="user_name"
                    ),
                ),
                (
                    "user_email",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="user_email"
                    ),
                ),
                ("user_pw", models.CharField(max_length=128, verbose_name="user_pw")),
                (
                    "user_is_staff",
                    models.BooleanField(default=False, verbose_name="user_is_staff"),
                ),
                (
                    "user_last_login",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="user_last_login"
                    ),
                ),
                (
                    "user_register_dttm",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="user_register_dttm"
                    ),
                ),
            ],
        ),
    ]
