# Generated by Django 4.1 on 2023-05-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userService", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.DeleteModel(name="User",),
    ]
